# Generated by Django 3.2.17 on 2023-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
