# Generated by Django 3.2.17 on 2023-03-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20230313_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
