# Generated by Django 3.2.18 on 2023-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('Blog', '0004_blogcomment_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='category.Category'),
        ),
    ]
