# Generated by Django 4.1.7 on 2023-04-01 10:52

import Blog.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='minute_read',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=Blog.models.user_directory_path),
        ),
    ]
