# Generated by Django 4.1.7 on 2023-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('Blog', '0006_blog_minute_read_alter_blog_body_alter_blog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
