# Generated by Django 4.1.7 on 2023-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('counsel', '0002_counselroom_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselroom',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
    ]
