# Generated by Django 4.1.7 on 2023-06-19 12:13

import authy.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=20)),
                ('profile_info', models.TextField(blank=True, max_length=259, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('gender', models.CharField(choices=[('none', 'None'), ('male', 'Male'), ('female', 'Female')], default='none', max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('picture', models.ImageField(blank=True, default='./user.png', null=True, upload_to=authy.models.user_directory_path, verbose_name='picture')),
                ('created', models.DateField(auto_now_add=True)),
                ('favorite', models.ManyToManyField(blank=True, to='Blog.blog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
